# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

To get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
!pip install numpy   ##Installing numpy inside the jupyter notebook



[notice] A new release of pip available: 22.1.2 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

Advantsges of numpy array over lists

1. Numpy is fast and lists are slow. For numpy a value is stored in binary form eg int32 while lists are bult in integer type and consist of size, reference count, object type, object value.
2. Faster to read due to less bytes of memory.
3. Numpy utilizes contiguous memory

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:


In [5]:

array1=np.array([[[[[5,6,7.3,8,9],[2,3,4,5,6]]]]],dtype="int64")
array1.dtype
array1

array([[[[[5, 6, 7, 8, 9],
          [2, 3, 4, 5, 6]]]]], dtype=int64)

In [5]:
my_list = [1,2,3]
my_list
#type(my_list)
#my_list.dtype #--normal lists do not have data type

[1, 2, 3]

Every time we use a numpy functionality we use the np prefix to say whatever comes after that comes from the numpy package.

In [3]:
import numpy as np

In [4]:
arr1=np.array(my_list)
arr1

array([1, 2, 3])

In [8]:
arr1=np.array(my_list)
arr1=np.array([1.0,2,3,4])
print(arr1)
print(arr1)
type(arr1) #The nd in the output stands for n (which can be 1,2,3,4,5) dimension
print(arr1.dtype)

[1. 2. 3. 4.]
[1. 2. 3. 4.]
float64


In [10]:
arr=np.array([1,2,4,9,7,8])
arr.dtype   #arr.dtype #It a short form for data type. Means that every value that we put inside it is of the type int32. 
          #Int stands for integer(whole number) and how many bits is used to represent that number(32 bits)
    
    
#arr

dtype('int32')

In [7]:
a=np.array([1,2,3,4,5,7],dtype="float64") 
a.dtype
#print(a)
print(a.ndim) ##checking the dimension
print(a.size)
print(a.shape)
#a[2]=0 #extracting and replacing the elements inside the array
#print(a)
a[3]

1
6
(6,)


4.0

In [11]:
p=np.array([1,1,1.4])
print(p)
print(type(p))

[1.  1.  1.4]
<class 'numpy.ndarray'>


In [19]:
f=np.array([[[1,2,3,4,5,6.2]]])
f.ndim

3

In [9]:
f=np.array([1,2,3,4,5,6.2])
print(f.dtype) #Has floating data number ie fractional numbers
#indexing
f[0]
f[2]=11 #converted to a float cs the array is a float
f.fill(-4)#Replaces everything with 4
print( f.ndim)# returns the number of dimensions
f.shape #shows the number of elements along each dimension
f.size# Returns the number of elements in the array

float64
1


6

**Universal Functions**

In [25]:
a=np.array([1,2,3,4,5,6.2])
print(np.sin(a)) #Computes the sin of every element of f
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.0830894 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.9965421 ]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.08337771]


In [31]:
y=[[1,2,3,4],[10,11 ,12,13]] #nested list
y[1][3]

13

**Multi-dimensional Arrays**

In [33]:
matrix=np.array([[1,2,3,4],[10,11 ,12,13]])
matrix

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [41]:
print(a.shape) # (rows, columns)-Outermost list has inside of it two lists and each of the inner list has 4 elements
print(a.size) #Total number of elements(product of the shape)
print(a.ndim) #length of the shape

(2, 4)
8
2


## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [34]:
np.arange(0,26) ##The upper limit is not included

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [35]:
np.arange(0,11,3)# 3 shows the value the sequence will increase by

array([0, 3, 6, 9])

### zeros and ones

Generate arrays of zeros or ones

In [36]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [38]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
np.ones(3)

array([1., 1., 1.])

In [45]:
a=np.ones((3,3,2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [46]:
a=np.ones((4,2), dtype="float64") #You can specify the data type
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### any other value

In [47]:
a.shape

(4, 2)

In [39]:
b=np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.full_like(b,9)

array([[9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9.]])

In [41]:
np.full_like(b,4) #a must be defined

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [42]:
a=np.full(b.shape,16)
a

array([[16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16]])

In [7]:
np.empty(b.shape) ##check what it does

NameError: name 'np' is not defined

### linspace
Return evenly spaced numbers over a specified interval.

In [9]:
import numpy as np
np.linspace(0,10,2) #Three elements between 0 an 10

array([ 0., 10.])

In [55]:
np.linspace(0,10,50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye or identity

Creates an identity matrix

In [2]:
import numpy as np

In [44]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(2,2)


array([[1., 0.],
       [0., 1.]])

In [46]:
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [47]:
np.random.rand(5)

array([0.05111825, 0.95215516, 0.50434684, 0.2103577 , 0.25981276])

In [10]:
np.random.rand(5,5) #creates a matrix of random numbers between 0 and 1

array([[0.7886025 , 0.98195231, 0.81673499, 0.70345728, 0.00552045],
       [0.07596816, 0.66847831, 0.04056108, 0.56012008, 0.78925508],
       [0.51274584, 0.09214105, 0.59494757, 0.78636533, 0.62632795],
       [0.01961373, 0.87955226, 0.71795038, 0.21286334, 0.86689725],
       [0.59872456, 0.6862865 , 0.21020657, 0.97158561, 0.84617498]])

In [20]:
np.random.random_sample(6)

array([0.8261679 , 0.9056727 , 0.61068092, 0.83709399, 0.26462582,
       0.94983062])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:
With a mean of zero and a standard deviation of 1. data~N(0,1)

In [21]:
np.random.randn(10)

array([-1.88436869,  0.55922938,  0.95763382, -0.60675395,  0.27850309,
        1.31009799, -1.90686657, -0.70299662,  0.3767091 , -1.41107488])

In [19]:
np.random.randn(5,5)

array([[ 0.63299963, -0.06515444,  0.49750358,  0.77288684, -0.02693147],
       [-0.4542713 ,  0.0295765 ,  1.24897868,  0.35972798,  0.36226007],
       [-1.33599688,  0.13959165, -3.6250092 ,  1.72810543, -1.90042346],
       [-0.0759669 ,  0.70582982, -0.20547447, -1.19612171,  0.1607388 ],
       [-1.75663058, -0.59298069, -0.41636971, -0.03868956,  0.9767362 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [11]:
np.random.randint(1,100,5)

array([41, 87, 23, 16, 47])

In [17]:
np.random.randint(1,100,10)

array([30, 69, 88, 63, 92, 22,  6, 44, 77, 49])

In [30]:
np.random.randint(7, size=(3,3)) #Starts from zero without start value.

array([[3, 4, 5],
       [4, 4, 5],
       [5, 6, 1]])

In [31]:
np.random.randint(4,7, size=(3,3)) #Assigns random number from 4 to 7 on a 3 by 3 array and 7 is not included

array([[6, 4, 4],
       [4, 5, 6],
       [5, 4, 4]])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [15]:
arr = np.arange(25) #Prints one dimension array
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [17]:
ranarr = np.random.randint(0,50,10)
print(ranarr)

[29 11 11  2 26  5 39  1 26 40]


## Reshape
Returns an array containing the same data with a new shape.

In [19]:
b=arr.reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)
a
a.reshape(4,2)
#a.ndim

(2, 4)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### max,min,argmax,argmin, sum,sqrt

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [50]:
ranarr

array([ 8, 35,  6, 44,  1,  7, 42, 15, 24, 48])

In [51]:
ranarr.max()

48

In [52]:
ranarr.argmax()  #Gives the location of the maximum value

9

In [53]:
ranarr.min()

1

In [54]:
ranarr.argmin() #Gives the location of the minimum values

4

In [55]:
ranarr.sum()

230

In [56]:
np.sqrt(ranarr)  #Returns square root of all the elements

array([2.82842712, 5.91607978, 2.44948974, 6.63324958, 1.        ,
       2.64575131, 6.4807407 , 3.87298335, 4.89897949, 6.92820323])

In [39]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
print(a.sum(axis=1))


[10 26]


In [51]:
a.sum(axis=0)  #column sum
a.sum(axis=1)  #Rows sum
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.sum(axis=None))
print(a.mean(axis=0)) #columns mean
print(a.mean(axis=1))  #Rows mean
print(a.mean(axis=None))

[ 6  8 10 12]
[10 26]
36
[3. 4. 5. 6.]
[2.5 6.5]
4.5


### Broadcasting

In [53]:
x="science"
y="data" ##concatenation
z=y + x
print (z)
y=[1,2,3,4,5]
x=[[1,2,3,4],[4,5,6,7]]##nested list
c=y+x
c



datascience


[1, 2, 3, 4, 5, [1, 2, 3, 4], [4, 5, 6, 7]]

In [109]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,1,9])
print(a.shape)
#b.shape
c=a+b
print(c)

(3, 3)
[[ 2  3 12]
 [ 5  6 15]
 [ 8  9 18]]


In [71]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,1,9])
print(a.shape)
print(b.shape)
print(a.ndim)
print(b.ndim)
print(a.dtype)
print(b.dtype)
#b.shape
c=a+b
print(a)
print(b)
print(c)#We dont need to have array of the same dimension and shape
b.ndim
#print(a.shape)

#print(b.shape)

#print(c)

(3, 3)
(3,)
2
1
int32
int32
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 1 9]
[[ 2  3 12]
 [ 5  6 15]
 [ 8  9 18]]


1

## Shape

Shape is an attribute that arrays have (not a method):

In [73]:
# Vector
arr = np.arange(25)
arr.shape
arr.ndim
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
# Notice the two sets of brackets
arr2=arr.reshape(1,25)
arr2.ndim
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [75]:
arr.reshape(1,25).shape

(1, 25)

In [83]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [76]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [71]:
arr.dtype

dtype('int32')

### Concatenate

In [65]:
a=np.array([[1,2], [4,5]])
b=np.array([[7,8]])
c=np.concatenate((a,b))
print(c)
a.ndim
b.ndim

[[1 2]
 [4 5]
 [7 8]]


2

**Numpy.ravel()** 

It converts the entire array into a single column

In [66]:
c.ravel()

array([1, 2, 4, 5, 7, 8])

### Array indexing and  slicing

In [5]:
a=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
a

NameError: name 'np' is not defined

In [73]:
##a[rows,columns]

a[2:5:2,1:5:3]

array([[21, 24],
       [41, 44]])

In [86]:
a[0:4:3,0:5:4]

array([[ 0,  4],
       [30, 34]])

In [139]:
a=np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [40]:
ab=a.reshape(6,6)
ab

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [74]:
ab[0:4:3,0:5:2]

array([[ 0,  2,  4],
       [30, 32, 34]])

In [75]:
ab[0:6:5,]

array([[ 0,  1,  2,  3,  4,  5],
       [50, 51, 52, 53, 54, 55]])

In [81]:
ab[3:6:2,1:6:2]

array([[31, 33, 35],
       [51, 53, 55]])

In [77]:
ab[0:6:5,0:3:1]

array([[ 0,  1,  2],
       [50, 51, 52]])

In [97]:
a[4:,] #Row four and all the columns
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [103]:
a[0,3::2] #To extract element 3 and five in row 1(2 denotes a jump of two)

array([3, 5])

In [98]:
a[:, 4] #extracting column 5

array([ 4, 14, 24, 34, 44, 54])

In [99]:
a[2,2]

22

In [100]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [104]:
a[:,1::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25],
       [31, 33, 35],
       [41, 43, 45],
       [51, 53, 55]])

# Chapter 1 Assignment
1. Create a null array of size 10 but the fifth value which is 1....done
2. Reverse a above created array (first element becomes last)...done
3. Create a 3x3 matrix with values ranging from 0 to 8..done
4. Find indices of non-zero elements from [1,2,0,0,4,0]
5. Create a 3x3x3 array with random values...done
6. Create a 10x10 array with random values and find the minimum and maximum values
7. Create a random vector of size 30 and find the mean value
8. Create a 2d array with 1 on the border and 0 inside
9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
10. Extract the integer part of a random array
11. Create a 5x5 matrix with row values ranging from 0 to 4
12. Create a random vector of size 10 and sort it
13. Consider two random array A anb B, check if they are equal
14. How to tell if a given 2D array has null columns?
15. Considering a four dimensions array, how to get sum over the last two axis at once?
16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

THE END.
PPANDS NEXT....

Additional materials
https://www.pythoncheatsheet.org/cheatsheet/dictionaries